CREATE TABLE IF NOT EXISTS Bike (id VARCHAR(100), manufacturer VARCHAR(100));
CREATE TABLE IF NOT EXISTS Color(id VARCHAR(100), bike_id VARCHAR(100), r INTEGER, g INTEGER, b INTEGER, painted_above VARCHAR(100))
